### ISSUE TITLE
net/wireguard

### ISSUE THREAD

**Issue by ghost** [ananjaser1211/Helios_7870#4]
That script is sometime working sometimes not , its  not abling to create wireguard folder in net/ and failing build , so kindly update wireguard script or prebuilt it

**Comment by kikekun3008** [comment]
@arsenalbot Let Anan give 0 fucks

**Comment by ananjaser1211** [comment]
> That script is sometime working sometimes not , its not abling to create wireguard folder in net/ and failing build , so kindly update wireguard script or prebuilt it

https://github.com/ananjaser1211/Helios_7870/blob/Helios_V4/arch/arm64/configs/helios_defconfig#L16

Disable it from here for now, until i see why the script is no longer working. i have a local copy of the wireguard package so it never failed here
